### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by iwebgit** [einteractive/teejakohv#19]
- [x] Выпадающую корзину выставить по правому боку container.
- [x] Расширить самый верхний row, в online сузился.
- [x] Убрать page.php из страниц строку.
- [x] 25.11 - При загрузке шестеренка загрузки перестала быть круглой, необходимо, чтобы она была круглой.
<img width="346" alt="screen shot 2017-11-25 at 13 29 21" src="https://user-images.githubusercontent.com/32779386/33230065-b82795f4-d1e4-11e7-8f73-9ed3c4ba1e74.png">

#### Нужно
- [x] Логотип закасчика

#### Важно уточнить, нужно ли?
- [x] Mini cart hidden when you in cart page
- [x] Mini cart not add in life time, not using ajax

#### Search results
- [ ] Выставить топ товаров?!
<img width="346" alt="screen shot 2017-11-25 at 13 29 21" src="https://user-images.githubusercontent.com/13300890/33244687-790a56a6-d304-11e7-95ec-03d831e1d746.jpg">

**Comment by dmitri-jurovski** [comment]
Фотография на фоне, jquery ошибка и еше немного исправлений Содержит в себе Pull
